apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: patient-management

spec:
  selector:
    app: doctor-service

  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003

  type: ClusterIP
