spring.application.name=auth-service
server.port=4005
#spring.profiles.default=test
spring.profiles.active=local

jwt.secret=MzJieXRlc2VjcmV0a2V5Zm9yYXV0aG1lc2VydmljZXM=
eureka.client.service-url.defaultZone=${APP_EUREKA_URL:http://localhost:8761/eureka/}


management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable data.sql execution after Hibernate schema creation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.forward-headers-strategy=framework