apiVersion: v1
kind: Service
metadata:
  name: clinical-service
  namespace: patient-management

spec:
  selector:
    app: clinical-service

  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007

  type: ClusterIP