apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-service
  namespace: patient-management

spec:
  replicas: 1

  selector:
    matchLabels:
      app: clinical-service

  template:
    metadata:
      labels:
        app: clinical-service

    spec:
      containers:
        - name: clinical-service

          image: ghcr.io/tranhuong0204/mscnptpm/clinical-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 4007

          env:
            - name: SERVER_PORT
              value: "4007"

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/clinical_db"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: APP_DDL_AUTO
              value: "update"

            - name: APP_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

            - name: APP_EUREKA_URL
              value: "http://eureka-server:8761/eureka/"

            - name: APP_PATIENT_SERVICE_URL
              value: "http://patient-service:4000"

            - name: APP_DOCTOR_SERVICE_URL
              value: "http://doctor-service:4003"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 4007
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 4007
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi