services:

  postgres:
    ports: !reset []

  eureka-server:
    build: !reset null
    image: ${IMAGE_PREFIX}/eureka-server:latest
    ports: !reset []

  auth-service:
    image: ${IMAGE_PREFIX}/auth-service:latest
    ports:
      - "4005:4005"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  patient-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/patient-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  doctor-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/doctor-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  clinical-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/clinical-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  billing-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/billing-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  appointment-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/appointment-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  pharmacy-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/pharmacy-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  analytics-service:
    build: !reset null
    image: ${IMAGE_PREFIX}/analytics-service:latest
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build: !reset null
    image: ${IMAGE_PREFIX}/api-gateway:latest
    ports:
      - "4004:4004"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  kafka:
    ports: !reset []