apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-management

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service

          image: ghcr.io/tranhuong0204/mscnptpm/auth-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 4005

          env:
            # Spring Boot
            - name: SPRING_PROFILES_ACTIVE
              value: "local"

            - name: SERVER_PORT
              value: "4005"

            # PostgreSQL
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/auth_db"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_PASSWORD

            # JPA
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # Eureka
            - name: EUREKA_CLIENT_ENABLED
              value: "true"

            - name: APP_EUREKA_URL
              value: "http://eureka-server:8761/eureka/"

            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 4005
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 4005
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: auth-service
#  namespace: patient-management
#
#spec:
#  replicas: 1
#
#  selector:
#    matchLabels:
#      app: auth-service
#
#  template:
#    metadata:
#      labels:
#        app: auth-service
#
#    spec:
#      containers:
#        - name: auth-service
#
#          image: ghcr.io/tranhuong0204/mscnptpm/auth-service:latest
#          imagePullPolicy: Always
#
#          ports:
#            - containerPort: 4005
#
#          env:
#            - name: SERVER_PORT
#              value: "4005"
#
#            - name: DB_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: auth-secret
#                  key: DB_USERNAME
#
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: auth-secret
#                  key: DB_PASSWORD
#
#            - name: DB_URL
#              value: "jdbc:postgresql://postgres:5432/auth_db"
#
#            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
#              value: "http://eureka-server:8761/eureka/"
#
#            - name: JWT_SECRET
#              valueFrom:
#                secretKeyRef:
#                  name: auth-secret
#                  key: JWT_SECRET