apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: patient-management

spec:
  type: ClusterIP

  selector:
    app: auth-service

  ports:
    - name: http
      port: 4005
      targetPort: 4005