
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: patient-management
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: 'Tranhuong222@'
  JWT_SECRET: MzJieXRlc2VjcmV0a2V5Zm9yYXV0aG1lc2VydmljZXM=