apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: patient-management
spec:
  type: ClusterIP

  selector:
    app: zookeeper

  ports:
    - name: client
      port: 2181
      targetPort: 2181