spring.application.name=patient-service
server.port=4000
spring.profiles.default=local

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${APP_DDL_AUTO:update}
spring.kafka.bootstrap-servers=${APP_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
eureka.client.service-url.defaultZone=${APP_EUREKA_URL}
logging.level.root=info

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoint.health.show-details=never

